
# gem 'activerecord', '5.2.3'
# gem 'sinatra-activerecord'
# gem 'sqlite3'
# gem 'sinatra'
# gem 'rake'
# gem 'thin'
# gem 'shotgun'
# gem 'pry'
# gem 'require_all'

gem 'activerecord', '5.2.3'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'